// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iyzymvvxgtmtjmrgtatg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5enltdnZ4Z3RtdGptcmd0YXRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3OTEzMTIsImV4cCI6MjA2NjM2NzMxMn0.tQGhX0JX7USbHGRehFGFp_jvNz4wwOzkKekNIZF_fsU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);